# Generated by Django 5.0.7 on 2024-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_data',
            field=models.TextField(default={}),
        ),
    ]
