# Generated by Django 5.0.7 on 2024-07-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
