# Generated by Django 5.0.7 on 2024-07-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_post_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_comments',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_reactions',
            new_name='reaction_count',
        ),
    ]
