# Generated by Django 5.0.7 on 2024-07-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='status',
        ),
    ]
