# Generated by Django 5.0.7 on 2024-07-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_connection_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
    ]
