# Generated by Django 5.0.7 on 2024-07-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('social', '0011_alter_connection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('user_from', 'user_to')},
        ),
    ]
